Synaptic "" {
  packageColumnWidth "200";
  instVerColumnWidth "130";
  availVerColumnWidth "130";
  ViewMode "0";
  showWelcomeDialog "1";
  vpanedPos "240";
  hpanedPos "200";
  windowWidth "1088";
  windowHeight "724";
  windowX "330";
  windowY "22";
  ToolbarState "2";
  Maximized "0";
  Install-Recommends "1";
};
