#extra-keys = [ \
#    ['F1','F2','F3','F4','F5','F6','PGUP','HOME','UP','END',{key: KEYBOARD, popup: DRAWER}], \
#    ['F7','F8','F9','F10','F11','F12','PGDN','LEFT','DOWN','RIGHT','ESC'] \
#]
extra-keys = [['PASTE', 'DRAWER', {key: KEYBOARD, popup: DRAWER}]]

allow-external-apps = true

# fullscreen = true

# use-fullscreen-workaround = tarue

# Open a new terminal with ctrl + t (volume down + t)
shortcut.create-session = ctrl + t

# Go one session down with (for example) ctrl + 2
shortcut.next-session = ctrl + 2

# Go one session up with (for example) ctrl + 1
shortcut.previous-session = ctrl + 1

# Rename a session with (for example) ctrl + n
shortcut.rename-session = ctrl + u

# Beep with a sound.
# bell-character=beep

# Cursor Blinking
terminal-cursor-blink-rate=100


key.extra-keys.home = '[H'
key.extra-keys.end = '[F'
key.extra-keys.pgup = '[5~'
key.extra-keys.pgdn = '[6~'


#fullscreen=true

terminal-margin-horizontal=0
terminal-margin-vertical=0
